### ISSUE TITLE
Passing a command with spaces on Windows doesn't work

### ISSUE THREAD

**Issue by DomiQ** [mikehaertl/php-shellcommand#1]
<b>Sorry for moving the thread around, I got really confused with all the code.</b>
When I try passing this as an exaple:
 
     '..\..\..\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe http://localhost/Ponudomat/printRdy.php print.pdf'

The program returns this:

    '..\..\..\Program' is not recognized as an internal or external command, operable program or batch file.

It separates the DIR into different commands because of the spaces, to fix it you need to pass the DIR within the "" and that's where the problem kicks in.

When I try:

     '"..\..\..\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" http://localhost/Ponudomat/printRdy.php print.pdf'

I just keep getting the same error as the one above.
When I try adding "/ instead of " to try and force php into making a quote within a string.
This is the confusing part, when I put:

     '"/..\..\..\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"/ http://localhost/Ponudomat/printRdy.php print.pdf'

It actually runs the command and partially works. So now I got the .exe running but it gives me an error as it cannot read the parameters it needs because of the "/ so I get:

    Loading pages (1/6) [> ] 0% [===> ] 5% [======> ] 10% Error: Failed loading page file:///C:/ (sometimes it will work just to ignore this error with --load-error-handling ignore) [========> ] 14% [=========> ] 15% [==========> ] 17% [============> ] 20% [=================================> ] 55% Exit with code 1 due to network error: ContentOperationNotPermittedError

Because the command is as follows <b>getCommand</b>:

    /..\..\..\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"/ http://localhost/Ponudomat/printRdy.php print.pdf

**Comment by mikehaertl** [comment]
Here's [a comment](http://php.net/manual/en/function.proc-open.php#119134) from the `proc_open()` PHP manual page that seems to address and solve the issue:

> If you are working on Windows and try to proc_open an executable that contains spaces in its path, you will get into trouble.

> But there's a workaround which works quite well. I have found it here: http://stackoverflow.com/a/4410389/1119601

> For example, if you want to execute "C:\Program Files\nodejs\node.exe", you will get the error that the command could not be found.
>Try this:
> ```
> <?php
$cmd = 'C:\\Program Files\\nodejs\\node.exe';
if (strtolower(substr(PHP_OS,0,3)) === 'win') {
    $cmd = sprintf('cd %s && %s', escapeshellarg(dirname($cmd)), basename($cmd));
}
?>

**Comment by mikehaertl** [comment]
@DomiQ In case you're still there: If I add the above fix, would you be available for testing? Because I don't use Windows.

**Comment by DomiQ** [comment]
I can test it sure, but I've got a bunch of projects to finish for college.
So I'll test it but probably not in the coming month.

**Comment by mikehaertl** [comment]
That's great. I've pushed the fix to master. Maybe you find the time for a quick test. I could also create a release, if that's easier for you.

**Comment by DomiQ** [comment]
Ok, great, master is fine. I'll test it when I find some free time.

**Comment by mikehaertl** [comment]
@DomiQ Ping ;). Did you maybe find a minute to give this a quick try? Should really not be hard to test. I just don't have Windows here so can't test it myselft.

**Comment by DomiQ** [comment]
@mikehaertl I'm just now rerunning home from a trip so I can give it a run tonight or tomorrow morning and report back. :)

**Comment by DomiQ** [comment]
I've tested the commit on a project I worked on back when the issue started and I can confirm that it works. I've also just tried pushing some bigger commands trough it and they all worked.

**Comment by mikehaertl** [comment]
Great news! Thanks! So I'll close this and prepare release 1.2.1.
