### ISSUE TITLE
Real time output

### ISSUE THREAD

**Issue by schmunk42** [mikehaertl/php-shellcommand#11]
Is there a way to show the realtime output of a long running command on the console?

Similar to what's described [here](http://stackoverflow.com/q/1281140/291573).

**Comment by mikehaertl** [comment]
Hmm, no and I currently don't really have plans to implement something like this. Would have to think about a nice and easy OO interface first. But let's keep it open as a feature request. But I would not wait for it ;).

**Comment by schmunk42** [comment]
Draft for discussion: https://github.com/schmunk42/php-shellcommand/commit/1606eeffedfdc1a77ae19cf56f9c0c1edc780648

CC: @phpnode

**Comment by schmunk42** [comment]
From the discussions in the commit:

> Yes, sure. Just fetch the final command string from getExecCommand().

Great :) So this is basically just a little example for the docs.

**Comment by Antoniossss** [comment]
+1 - live output is needed for example on long running processes. My proposition of solving this is in https://github.com/Antoniossss/php-shellcommand/tree/issue-11-live-output fell free to fetch those changes. As a feature requirement i am using that code right now.

**Comment by schmunk42** [comment]
> Another solution would be to expose additional output pipe for the user to fetch directly from the stream insteed of echoing everything right away, or even allow user to define his own stream that output should be piped to.

That sounds nice to me.

**Comment by mikehaertl** [comment]
How about a callback? You could configure it with the class and whenever there's a new output fragment the function is called. Would that make sense? If we do that, we should also think if we need different callbacks for stdout and sterr. I have to admit that I'm not really an expert on continuous output of commands. So more feedback welcome.

> Another solution would be to expose additional output pipe for the user to fetch directly from the stream 

Yes, that's what I also considered. But this again makes things ugly. Developers should not have to deal with pipes if possible.

**Comment by Antoniossss** [comment]
@mikehaertl Callback would also make sense and would satisfy both of us - there would be no direct output - just as you wanted, and I would have possibility to echo incoming data in realtime. 
Also it would make sense to have stdOut callback and stdErr callback just in case if stdErr is not redirected to stdOut. 
The flag to echo output i made can be simply replaced by the callback - if not null, pass current output to callback.

**Comment by mikehaertl** [comment]
Closing this as an implementation is far from trivial and would cause too many headaches. Also see my comment here: https://github.com/mikehaertl/php-shellcommand/pull/27#issuecomment-522214074
