### ISSUE TITLE
Imrove error reporting

### ISSUE THREAD

**Issue by mikehaertl** [mikehaertl/php-shellcommand#15]
It seems to be the case that the return value of `proc_close()` is not really reliable. So sometimes it reports an error, even if everything went fine. We should improve this somehow.

**Comment by dreizwo** [comment]
For me too. I get exitCode 1 instead of !==0. When changing line 324 in Command.php 
from 
```
 if ($this->_exitCode!==0) {
....
}
```
into
```
 if ($this->_exitCode==-1) {
....
}
```
everything works fine

**Comment by brutalcrozt** [comment]
as [here](https://github.com/mikehaertl/php-pdftk/issues/87) i think it's related to this. Right now i still can't find reliable way to reproduce my problem, But this capture should show you the basic expectation. I use new PC but i was forgot to install `pdftk` first, before using `php-pdftk`.
![php shell command](https://user-images.githubusercontent.com/3001652/30057567-625270d0-9261-11e7-9aa7-9d52ff84e5b2.PNG)

i was expecting `pdftk command not found` or something similar. And with that will give usefull error message.

**Comment by mikehaertl** [comment]
Catching the error message has been completely refactored in #41 so this should no longer be an issue.
