### ISSUE TITLE
Windows command from different drive letter fails

### ISSUE THREAD

**Issue by corsal** [mikehaertl/php-shellcommand#16]
If my php file is being executed from my E:\ drive to a command running on my C:\ drive, it doesn't work since the cd is happening on the wrong drive.

I fixed it by doing the following:
`$drive = substr($command, 0, 2);`
`$command = sprintf($drive . ' && cd %s && %s', escapeshellarg(dirname($command)), basename($command));`

So $command becomes:
C: && cd "C:\Program Files\wkhtmltopdf\bin" && wkhtmltopdf.exe

**Comment by mikehaertl** [comment]
@corsal I've supplied a fix on master. Can you help testing please?

**Comment by mikehaertl** [comment]
@DomiQ As you're also on Windows, maybe you can also confirm that this change doesn't break anything? Also it should work with both, a full path like `C:\\foo\bar.exe` and a relative path like `bar.exe` if this is in your search path.

**Comment by corsal** [comment]
@mikehaertl Yes, this fix worked great. Thanks!

**Comment by mikehaertl** [comment]
Released 1.2.2 which includes this fix. Thanks!
