### ISSUE TITLE
Executing a file with a relative path on Windows is broken

### ISSUE THREAD

**Issue by takobell** [mikehaertl/php-shellcommand#22]
If I pass in a relative path on Windows to execute (assuming what I want to execute is already in the working directory or in my PATH environment variable), it produces incorrect output.

For example:

    mysqldump --defaults-extra-file=C:\temp\my.cnf --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --result-file=C:\temp\backup.sql testdatabase

Will produce:

    cd "mysqldump --defaults-extra-file=C:\temp\my.cnf --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --result-file=C:\temp" && backup.sql testdatabase

It looks like https://github.com/mikehaertl/php-shellcommand/commit/d9a0e8ecff24badfe07129630a67c3d19e31a094 is really only a fix for absolute paths.

**Comment by takobell** [comment]
pull request incoming!

**Comment by takobell** [comment]
Thoughts on this one?

**Comment by mikehaertl** [comment]
@takobell Ouch, I'm sorry. I was confused about the new "Start a review" feature on Github and just found out, that I had to submit my comments first before you can see it. It was lingering there for month.

**Comment by takobell** [comment]
@mikehaertl No worries... still getting used to the new review tools myself.

**Comment by mikehaertl** [comment]
Just release 1.2.5 containing your fix. Thanks for your help!
