### ISSUE TITLE
wkhtmltopdf processes becomes zombie

### ISSUE THREAD

**Issue by drmax24** [mikehaertl/php-shellcommand#24]
In our code that uses mikehaertl/phpwkhtmltopdf we have an option:
['window-status'=>'ready-to-print']

However on some occasions ready-to-print is not set in js. In this case wkhtmltopdf processes will never stop. And after some time we have hundreds of zombie-processes. Is it possible to set max execution time for wkhtmltopdf?

https://github.com/mikehaertl/phpwkhtmltopdf/issues/223

P.S.:
ini_set('max_execution_time', 15);
Should do the job to kill php process and wkhtmltopdf with it right? It does not.

28378 www           1  20    0   213M 31292K piperd  5   0:01   0.00% php-fpm
28588 www           1  20    0   213M 31304K piperd  0   0:01   0.00% php-fpm

It hangs on piperead. max_execution_time apperantly does not work for piperead.

---
wkhtmltopdf -V
wkhtmltopdf 0.12.4 (with patched qt)

mikehaertl/php-shellcommand 1.2.4          
mikehaertl/php-tmpfile             1.1.0  
mikehaertl/phpwkhtmltopdf      2.2.1       

PHP 7.0.13 (php-fpm)

**Comment by mikehaertl** [comment]
Right. As I've said in https://github.com/mikehaertl/phpwkhtmltopdf/issues/223 the implementation is not so easy. AFAIK there's no feature in PHP to set a timeout for command execution. See http://php.net/manual/en/function.proc-open.php. If you find a way, let us know and we can try to implement it.

**Comment by francoism90** [comment]
@mikehaertl It is possible to use the Linux `timeout` command before the executable. Don't know if that is an option.

**Comment by mikehaertl** [comment]
@francoism90 Hmm, interesting idea. But we can't assume that this command is available everywhere. So if we add it, it should definitely be optional. It would also add quite some complexity to the library. Something which I try to avoid as much as I can to keep maintenance efforts for the library at a reasonable level :).

**Comment by francoism90** [comment]
@mikehaertl But it' s much more simple to just set timeout before the command.

**Comment by drmax24** [comment]
Any news on this?

**Comment by mikehaertl** [comment]
@drmax24 Unless you have a suggestion on how to solve it - no, no news here.

**Comment by mikehaertl** [comment]
@drmax24 Not sure if you're still interested but after the change in 1.5.0 it was now easy to implement a timeout feature. Any feedback on #42 welcome.

**Comment by mikehaertl** [comment]
Release 1.6.0 now contains the new `timeout` setting.
