### ISSUE TITLE
Can't run composer on Centos 7

### ISSUE THREAD

**Issue by AeolusIt** [mikehaertl/php-shellcommand#32]
When i tried run this code:
```
$command = new Command(ROOT_PATH. '/composer/ composer update');
$result = $command->execute())
```

I get this result:
sh: /var/www/mysite.com/public_html/composer/: Is a directory

**Comment by mikehaertl** [comment]
Remove the space between `/composer/` and `composer` in your command :unamused:

**Comment by AeolusIt** [comment]
Thanks, but  i tried it befure.

For that line i recive:

sh: /var/www/mysite.com/public_html/composer/composer: No such file or directory

**Comment by mikehaertl** [comment]
Then the path to that command either does not exist, or you are not allowed to call `proc_open()` on CentOS.

**Comment by AeolusIt** [comment]
function_exists("proc_open") recive me true.

In the composer directory i have only 2 files:
composer.json
composer.lock

On Windoows its work fine.

**Comment by mikehaertl** [comment]
Try if you can call proc_open(). I had a report recently that this is restricted on CenOS via php.ini by default. But I can't find it right now.

**Comment by mikehaertl** [comment]
See here: https://github.com/mikehaertl/phpwkhtmltopdf/issues/261

**Comment by AeolusIt** [comment]
The proc_open function on my vps work fine.
That code work:

`<?php
$descr = array(
    0 => array(
        'pipe',
        'r'
    ) ,
    1 => array(
        'pipe',
        'w'
    ) ,
    2 => array(
        'pipe',
        'w'
    )
);
$pipes = array();
$process = proc_open("ls -l", $descr, $pipes);
if (is_resource($process)) {
    while ($f = fgets($pipes[1])) {
        echo "-pipe 1--->";
        echo $f;
    }
    fclose($pipes[1]);
    while ($f = fgets($pipes[2])) {
        echo "-pipe 2--->";
        echo $f;
    }
    fclose($pipes[2]);
    proc_close($process);
}
?>`

**Comment by mikehaertl** [comment]
Then I don't know. Your error to me clearly indicates, that the command you try to execute does not exist.

This is not a problem of our library.

**Comment by AeolusIt** [comment]
Looks like you right...
When i tried run this line:

```
$command = new Command('cd ' . ROOT_PATH. '/composer/ && composer update');
$result = $command->execute());
```

I recived:
The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly  \n                                                                                            \n\nupdate [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
