### ISSUE TITLE
More secure keys addArg()

### ISSUE THREAD

**Issue by 4n70w4** [mikehaertl/php-shellcommand#38]
Case: `$command->addArg('; ls -la', 'something');`
Generated command: `cmd ; ls -la 'something'`
Сan execute any command on the server.

May be can do escapeshellarg for keys too.

**Comment by mikehaertl** [comment]
Developers should know, what they execute. We will not add any security checks as they would never work 100% and give a feeling of false safety.

**Comment by 4n70w4** [comment]
Is it necessary for cases in which arguments are obtained from users? Thought about it?

**Comment by schmunk42** [comment]
Obtaining commands from users is equivalent to giving them shell access.

**Comment by 4n70w4** [comment]
@schmunk42 I know. Say it to all customers. Therefore, additional security is not excessive.

**Comment by mikehaertl** [comment]
Sorry, I disagree. As a developer you're responsible for the code you write. There are millions of other ways you can open a security hole. We can't add warnings / safety checks everywhere.
