### ISSUE TITLE
Don't escape numeric values

### ISSUE THREAD

**Issue by 4n70w4** [mikehaertl/php-shellcommand#39]
Case: `$command->addArg('--arg', 123);`
Generated command: `cmd --arg '123'`
But this makes no sense.

May be skip escapeshellarg `if ctype_digit($value) === true`.

**Comment by 4n70w4** [comment]
Improved human-readability. It is very difficult to perceive the text of the command in which there are a lot of quotes. Well, this is true in conjunction with my neighboring issue.

**Comment by mikehaertl** [comment]
Humans are usually not supposed to see the generated command. If so, then maybe this library is not the right thing for them in the first place.

So unless you can show me where something is broken and doesn't work I'm closing this.
