### ISSUE TITLE
fgets and stream_set_blocking add `@` for disable warning output

### ISSUE THREAD

**Issue by Jamlee** [mikehaertl/php-shellcommand#43]
https://github.com/mikehaertl/php-shellcommand/blob/6c6f44cee9bef0d5e7670852d04128745de455ac/src/Command.php#L407-L408

https://github.com/mikehaertl/php-shellcommand/blob/6c6f44cee9bef0d5e7670852d04128745de455ac/src/Command.php#L463-L466

**Comment by mikehaertl** [comment]
Hmm, can you give an example how there could be a warning? IMO there should never be any.

**Comment by Jamlee** [comment]
yeah, php 7.4
![image](https://user-images.githubusercontent.com/5196641/70517167-1c682e00-1b73-11ea-917e-b89f2af46691.png)

**Comment by Jamlee** [comment]
![image](https://user-images.githubusercontent.com/5196641/70518583-93062b00-1b75-11ea-93cf-47f767aa4196.png)

**Comment by mikehaertl** [comment]
Hmm, the line numbers in your screenshot look weird: 460 and 457 are both comments. Did you modify the library files?

Also I'd prefer if we find out what is causing this and not supress the error. It should never happen that any value in `$pipes` is `null`.

**Comment by Jamlee** [comment]
no change anything, i just copy the single php to my project dir and add `@` templariure. before php 7.4, i got no warning too. So may be the php 7.4 problem.

**Comment by mikehaertl** [comment]
Can you show me your lines 457-460 of `Command.php`? I don't get why it reports errors there:
https://github.com/mikehaertl/php-shellcommand/blob/master/src/Command.php#L457

**Comment by mikehaertl** [comment]
For a proper fix I will also need your help: We need to find out, why `$pipes[1]` is suddenly closed. It should not be. 

You could add something like this to different places to find out where it happens:

```
if (!is_resource($pipes[1])) 
  die ('pipes 1 is now closed in line ' . __LINE__);
```

**Comment by Jamlee** [comment]
Sorry, it is the problem of swoole coroutine.  thanks for your useful help.
