### ISSUE TITLE
Support for nested commands

### ISSUE THREAD

**Issue by leo-unglaub** [mikehaertl/php-shellcommand#48]
Hey,
first of all, i love this lib. It works great. But now i have to generate a command that contains a nested command and i am not sure what the best way is. The command i want to generate looks like that this:

```
rsync -av --delete -e "ssh -i /home/user/.ssh/sshkey" root@server.example.com:/home/ /mnt/server-mirror/home/
```

What would be the best way to generate the **ssh -i /home/user/.ssh/sshkey** part?
Thanks and greetings
Leo

**Comment by mikehaertl** [comment]
Can't you just pass it as a string like `addArg('-e', 'ssh -i ...')`? It's just a string argument with spaces in it, so it be should properly escaped.

**Comment by leo-unglaub** [comment]
Hey,
i think i found a solution. I hope i am not creating a security problem with that solution, what do you think about this?

```php
$subcommand = new Command();
$subcommand->setCommand('ssh');
$subcommand->addArg('-v');
$subcommand->addArg('-i', '/home/user/.ssh/sshkey');

$command = new Command();
$command->setCommand('rsync');
$command->addArg('-a');
$command->addArg('-v');
$command->addArg('-e', $subcommand);
$command->addArg('root@server.example.com:/home/');
$command->addArg('/mnt/server-mirror/home/');
```

Thanks and greetings
Leo

**Comment by mikehaertl** [comment]
You should never get a securty problem (even if you pass data from a untrusted source to the command).

In your case I don't know, why you don't simply pass the subcommand as full string. Unless its args must be built dynamically there's no need to use this library.

For now I'm closing this as this is not a bug report. If you think something needs to be fixed or improved feel free to add another comment with some example.

**Comment by leo-unglaub** [comment]
I don't want to pass the subcommand as a full string because its also dynamically build. But you are right, that is not really a bug report anymore. I am going to patch your library. 
Thanks for your help mate!
