### ISSUE TITLE
Change shell and add PATH

### ISSUE THREAD

**Issue by Dibbyo456** [mikehaertl/php-shellcommand#49]
`exec()` or `proce_open()` or `shell_exec()` every commands internally calls `/bin/sh` (not `/bin/bash`) with `$PATH` as `/usr/bin:/bin`

1) Add ability to invoke `/bin/bash` or other shells.
2) Add ability to add `$PATH` variable before running the command.

Examples:

```php
$path_to_add = '/usr/local/bin/';
$command = 'export PATH=$PATH:' . $path_to_add; mycommand';
```
and

```php
exec("/bin/bash -c \"mycommand\"")
```

**Comment by mikehaertl** [comment]
Did you check the `procEnv` option where you can pass env vars? It should probably also accept a `$PATH`.

Also can you give me an example use case why you need a specific shell (bash)? The idea of the library was that you run a very specific command i.e. you usually should know the full path. So why would you rely on `$PATH` anyway?

**Comment by mikehaertl** [comment]
Closing this as there was no further feedback and I can't think of many use cases for this feature and adding new features increases maintenance costs for this library (bugfixing etc.). If you disagree, feel free to add more information why you think this is useful and should be added.
