### ISSUE TITLE
Undefined variable: pipes at src/Command.php line 288

### ISSUE THREAD

**Issue by eusonlito** [mikehaertl/php-shellcommand#5]
`$pipes` variable must be initalizated before to be passed as argument to `proc_open` function.

**Comment by mikehaertl** [comment]
Hmm, I don't think so. From the PHP manual:

> pipes
Will be set to an indexed array of file pointers that correspond to PHP's end of any pipes that are created.

It's not initialized in their example there either.

**Comment by eusonlito** [comment]
Ok, but my PHP 5.4.9 show this error :)

I had fixed it adding `$pipes = array();` in previous line.

**Comment by mikehaertl** [comment]
What is the error?

**Comment by eusonlito** [comment]
`Undefined variable: pipes at src/Command.php line 288`

**Comment by mikehaertl** [comment]
That makes no sense to me. Look at all the examples on this page:

http://php.net/manual/en/function.proc-open.php

They never initialize `$pipes`, not even in the comment section (where the probably also relate to older PHP versions). There's also a Travis configuration for PHP 5.4 which also runs fine.

So must be something else on your system.

**Comment by mikehaertl** [comment]
I found that some had this error if `proc_open()` was disabled on their system.

**Comment by eusonlito** [comment]
Ok, yes, my hosting have disabled `proc_open`, then `$pipes` never will be created from reference.

Thanks.

**Comment by schmunk42** [comment]
Wouldn't it make sense to add a check for this case?

**Comment by eusonlito** [comment]
`proc_open` and `shell` are basic PHP functions, then is my fault if I haven't checked the hosting limitations.

**Comment by mikehaertl** [comment]
@schmunk42 Agree to what @eusonlito said. If we start digging that hole, then you'd end up with checks for each and every PHP method.

**Comment by schmunk42** [comment]
Is the extension still usable when the setting is missing?

**Comment by mikehaertl** [comment]
Which setting do you mean?

**Comment by schmunk42** [comment]
Like when `proc_open` is disabled. 

I don't have this problem, but I just thought, since this extension is all about running shell commands, it's not wrong if it would warn you about a quirky setup. Similar to the feature of composer to require PHP-extensions. You could "require" certain settings and throw an exception otherwise.

>  then you'd end up with checks for each and every PHP method.

Yes and no. Just for the relevant ones.... just my 2 cents.
