### ISSUE TITLE
useExec apparently not working

### ISSUE THREAD

**Issue by wanwin** [mikehaertl/php-shellcommand#51]
Hi!

This is probably something that I'm overlooking but I want to comment it if I can help someone else in my situation.
```
$pdf = new Pdf([
  'command' => 'C:\Program Files (x86)\PDFtk Server\bin\pdftk.exe',
  'useExec' => true,
  'A' => $path1,   
  'B' => $path2
]);
$pdf->shuffle(1, 'end', 'A')
    ->shuffle(1, 'end', 'B')
    ->send('informe.pdf');
```

I was creating a new PDF that way, using 'command' and 'useExec' parameters, with php-pdftk library because my server has Windows as its OS, but I was always receiving the same error:
`Failed without error message: pdftk "command"="C:\Program Files (x86)\PDFtk Server\bin\pdftk.exe" "useExec"="1" "A"="C:\Windows\Temp\phpC9C7.pdf" "B"="C:\Windows\Temp\phpC9D7.pdf" shuffle A1-end B1-end "output" "C:\Windows\Temp\tmpC9D8.tmp.pdf" (Exit code: 1)`

To fix that error, I removed 'command' and 'useExec' parameters from the code shown above and changed the following condition in Command.php (line 378) from true to false because I noticed that, despite using 'useExec' parameter with true value, it wasn't changing it's value in that file and now there's no problem creating the PDF:
`if ($this->useExec) {`

Therefore, my doubt is, am I doing something wrong initializing the PDF or maybe is this a bug?

Thank you for your attention and for creating this awesome tools!

**Comment by mikehaertl** [comment]
You are missing the 1st argument (filename) to the constructor of `Pdf`. Command options must be passed as second argument.
