### ISSUE TITLE
Is it possible to reset state?

### ISSUE THREAD

**Issue by alexkuc** [mikehaertl/php-shellcommand#59]
Let me give you example. Say, you are executing command `/abs/path/bin`/. You set arguments via `addArg()`, then `execute()` and finally `getOutput()` or `getError()` or `getExitCode()`. All of these modifies internal state i.e. we remember output, exit code, etc.

Then, I reset args via `setArgs()` to empty. Add new args and execute again. But now how can I know if say `getOutput()` shows output of the first execution or second?

Currently, I am creating new instance of `php-shellcommand` for each new execution. Is there a more elegant way?

**Comment by mikehaertl** [comment]
The idea was really to create a new instance for each execution. If you need different args anyway I can't see why you would want to reuse the same instance.

It would only make sense if you want to execute the identical command with same args multiple times. I've not tried it but from looking at the code this should already be possible. The values for output, error and exitcode are reset each time you call `execute()`.
