### ISSUE TITLE
Improve proc_open() configuration

### ISSUE THREAD

**Issue by mikehaertl** [mikehaertl/php-shellcommand#6]
Issue https://github.com/mikehaertl/phpwkhtmltopdf/issues/78 describes a problem that could be fixed with a different pipe configuration, as found here:

http://php.net/manual/en/function.proc-open.php#97012.

I've adopted this in release 1.0.5:

```
1 => array('pipe', 'w'), // stdout
2 => array('pipe', 'a') // stderr
```

But this caused new problems as now error capturing seemed to be broken as reported in issue https://github.com/mikehaertl/phpwkhtmltopdf/issues/111.

So the change was undone in 1.0.6:

```
1 => array('pipe', 'w'), // stdout
2 => array('pipe', 'w') // stderr
```

A workaround would be, to use one or the other, depending on the OS. But so far I have no information from https://github.com/mikehaertl/phpwkhtmltopdf/issues/78 which OS is really affected. Windows was only my (unconfirmed) assumption.

**Comment by epicwally** [comment]
Responding to your comment on #9: It does seem to work with adding the stream_set_blocking() while leaving the pipe configuration the same.

**Comment by markdboyd** [comment]
@mikehaertl - I ran into this same issue as #20. And I can also confirm that adding the `stream_set_blocking()` lines while leaving the pipe configuration the same fixes it.

I'm on version 2.2.1 of `mikehaertl/phpwkhtmltopdf`, if that helps.

**Comment by mikehaertl** [comment]
@markdboyd I'm worried that changing things in the `proc_open()` code breaks other stuff again. It's so touchy. This happened before and I had to undo the changes. (See #20 and #21).

So before we don't have proper test cases to reproduce all these problems I'm still hesitant to change the code. I'd be more than happy if someone could help out here. We can continue discussion in #20.
