### ISSUE TITLE
on Windows, leaves a trailing quote in the command

### ISSUE THREAD

**Issue by jjdunn** [mikehaertl/php-shellcommand#63]
we have been using very old v0.4.4 for some years.  We had previously fixed a bug in that version but never reported it here.

today I tested v0.13.1 which has the same bug.  This is on Windows system.  PHP 8.1.20 with pdftk 2.02

`$command = ""C:\Program Files (x86)\PDFtk\bin\pdftk.exe""`
above is taken from xdebug: notice the value of `$command` has leading & trailing double-quote marks

see attached screenshot of debugger
![xdebug-shellcommand-command](https://github.com/mikehaertl/php-pdftk/assets/333222/dd90f288-70d5-47c8-a07f-838786a3291a)

patch:
```
--- /mikehaertl/shellcommand/Command-orig.php	Wed Apr 19 04:25:22 2023
+++ /mikehaertl/shellcommand/Command.php	Sun Nov 26 10:54:27 2023
@@ -195,9 +195,7 @@ class Command
                 // Could be a quoted absolute path because of spaces.
                 // i.e. "C:\Program Files (x86)\file.exe"
             } elseif (isset($command[2]) && $command[2] === ':') {
-                $position = 2;
+                // FIX THIS, it leaves a trailing quote
+                $command = trim($command, '"\'');
+                $position = 1;
             } else {
                 $position = false;
             }
```
without the change the executed command returns an error with no error-description.  the problem is it leaves the trailing quote-mark.

the fix simply removes the quotes - this has always worked properly on Windows.

**Comment by mikehaertl** [comment]
@jjdunn Moved here as the affected code is kept in this repo. For completeness could you please also show the part of your code where you configure the `'command'` option?

**Comment by jjdunn** [comment]
> For completeness could you please also show the part of your code where you configure the 'command' option?
```
//determine if the PDF is fillable
$pdfCommand = $app->params['helperApps']['MergePDF'];
$pdf = new EPdfTK($tempName, ['command' => $pdfCommand]);
$readFields = $pdf->getDataFields();  // this FAILS with the repo code; succeeds with the modified code
```

Our app is built on Yii 1.1 framework.  

configuration of the PdfTk executable:
```
'params' => [
  'helperApps' =>  [
     'HtmlToPDF' => '"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe"', 
     'ImageToPDF' => '"C:\Program Files\ImageMagick-7.1.0-Q8\\magick.exe"', 
     'MergePDF' => '"C:\\Program Files (x86)\\PDFtk\\bin\\pdftk.exe"', // v2.0.2 windows.  *HERE*
     'ghostScript' => '"C:\\Program Files\\gs\\gs9.54.0\\bin\\gswin64c.exe"', 
     'QPDF' => '"C:\\Program Files\\qpdf-10.3.2\\bin\\qpdf.exe"', 
  ]
]
```
hmmm...notice that the entire path to all the "helper" apps is double-quoted.  I guess this might be the cause of the problem.  It works for all the other executables though.

Here is the entire source of `EPdfTk` class (was this written by you?)
```
use mikehaertl\pdftk\Pdf;
include_once __DIR__ . DIRECTORY_SEPARATOR . 'mikehaertl' . DIRECTORY_SEPARATOR . 'tmp' . DIRECTORY_SEPARATOR . 'File.php';
include_once __DIR__ . DIRECTORY_SEPARATOR . 'mikehaertl' . DIRECTORY_SEPARATOR . 'shellcommand' . DIRECTORY_SEPARATOR . 'Command.php';
include_once __DIR__ . DIRECTORY_SEPARATOR . 'mikehaertl' . DIRECTORY_SEPARATOR . 'pdftk' . DIRECTORY_SEPARATOR . 'Command.php';
include_once __DIR__ . DIRECTORY_SEPARATOR . 'mikehaertl' . DIRECTORY_SEPARATOR . 'pdftk' . DIRECTORY_SEPARATOR . 'DataFields.php';
include_once __DIR__ . DIRECTORY_SEPARATOR . 'mikehaertl' . DIRECTORY_SEPARATOR . 'pdftk' . DIRECTORY_SEPARATOR . 'FdfFile.php';
include_once __DIR__ . DIRECTORY_SEPARATOR . 'mikehaertl' . DIRECTORY_SEPARATOR . 'pdftk' . DIRECTORY_SEPARATOR . 'Pdf.php';
include_once __DIR__ . DIRECTORY_SEPARATOR . 'mikehaertl' . DIRECTORY_SEPARATOR . 'pdftk' . DIRECTORY_SEPARATOR . 'XfdfFile.php';
class EPdfTK extends Pdf {
}
```

**Comment by jjdunn** [comment]
> could you first try to remove those double quotes from your command path? Our library should already handle that for you.

yes, that works.  with the surrounding double-quotes on the executable-path removed; and with the original (`$position=2;)` code restored, it works properly.

Sorry for raising an issue that doesn't exist.
